USE master
GO

USE TRABALHO_P
GO


CREATE PROCEDURE sp_GastosUltimoMes
AS
BEGIN
    SELECT CH.ID_HOSPITAL AS HospitalID, SUM(CH.SALARIO) AS TotalGastoHospital
    FROM Contratar_H CH
    WHERE CH.TEMPO >= DATEADD(MONTH, -1, GETDATE())
    GROUP BY CH.ID_HOSPITAL;

    SELECT CCS.ID_CS AS CentroSaudeID, SUM(CCS.SALARIO) AS TotalGastoCentroSaude
    FROM Contratar_CS CCS
    WHERE CCS.TEMPO >= DATEADD(MONTH, -1, GETDATE())
    GROUP BY CCS.ID_CS;

    SELECT SUM(ISNULL(CH.SALARIO, 0)) + SUM(ISNULL(CCS.SALARIO, 0)) AS TotalGastoTodosCentrosMedicos
    FROM Contratar_H CH
    FULL OUTER JOIN Contratar_CS CCS ON CH.TEMPO = CCS.TEMPO
    WHERE CH.TEMPO >= DATEADD(MONTH, -1, GETDATE()) OR CCS.TEMPO >= DATEADD(MONTH, -1, GETDATE());
END


EXECUTE sp_GastosUltimoMes


--DROP PROCEDURE sp_GastosUltimoMes