USE master
GO

CREATE DATABASE TRABALHO_PRATICO_D
GO

USE TRABALHO_PRATICO_D
GO

CREATE TABLE ESPACO_PUBLICO(
	ID						INTEGER		NOT NULL,
	Nome					VARCHAR(50) NOT NULL,
	Nome_Popular			VARCHAR(50) NOT NULL,
	Endereco_Morada			VARCHAR(50) NOT NULL,
	Endereco_Localidade		VARCHAR(50) NOT NULL,
	Endereco_CodigoPostal	CHAR(8)		NOT NULL,
	CHECK (Endereco_CodigoPostal LIKE '[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9]'),
	PRIMARY KEY (ID)
)

CREATE TABLE CIDADE(
	ID						INTEGER		NOT NULL,
	Nome					VARCHAR(50) NOT NULL,
	Area					INTEGER		NOT NULL,
	Localizacao				VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
)

CREATE TABLE LOCALIDADE( --chave primária??
	Localizacao_Continente				VARCHAR(50)			NOT NULL,
	Localizacao_Pais					VARCHAR(50)			NOT NULL,
	--PRIMARY KEY (Numero_Mecanografico, Numero, Data_Requisicao),
	FOREIGN KEY (Localizacao_Continente) REFERENCES CIDADE(Localizacao),
	FOREIGN KEY (Localizacao_Pais) REFERENCES CIDADE(Localizacao)
)

CREATE TABLE FUNCIONARIO(
	ID						INTEGER		NOT NULL,
	Nome					VARCHAR(50) NOT NULL,
	Apelido					VARCHAR(50) NOT NULL,
	Telefone				INTEGER		NOT NULL,
	Endereco				VARCHAR(50) NOT NULL,
	CHECK (Telefone LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
	PRIMARY KEY (ID)
)

CREATE TABLE RESIDENCIA( --chave primária??
	Endereco_Morada						VARCHAR(50)			NOT NULL,
	Endereco_Codigo_Postal				CHAR(8)				NOT NULL,
	Endereco_Localidade					VARCHAR(50)			NOT NULL,
	CHECK (Endereco_Codigo_Postal LIKE '[0-9][0-9][0-9][0-9]-[0-9][0-9][0-9]'),
	--PRIMARY KEY (Numero_Mecanografico, Numero, Data_Requisicao),
	FOREIGN KEY (Localizacao_Continente) REFERENCES FUNCIONARIO(Endereco),
	FOREIGN KEY (Localizacao_Pais) REFERENCES FUNCIONARIO(Endereco)
)

CREATE TABLE FREGUESIA(
	Codigo					INTEGER		NOT NULL,
	Area					INTEGER		NOT NULL,
	Populacao				INTEGER		NOT NULL,
	CHECK (Codigo LIKE '[0-9][0-9][0-9][0-9][0-9][0-9]'),
	PRIMARY KEY (Codigo)
)

CREATE TABLE CENTRO_MEDICO(
	ID						INTEGER			NOT NULL,
	Nome					VARCHAR(50)		NOT NULL,
	PRIMARY KEY (ID)
)

CREATE TABLE CENTRO_SAUDE(
	ID_CS					INTEGER			NOT NULL,
	Nome					VARCHAR(50)		NOT NULL,
	PRIMARY KEY (ID_CS),
	FOREIGN KEY(ID_CS) REFERENCES CENTRO_MEDICO(ID)
)

CREATE TABLE HOSPITAL(
	ID_H					INTEGER			NOT NULL,
	Especialidade			VARCHAR(50)		NOT NULL,
	PRIMARY KEY (ID_H)
	FOREIGN KEY(ID_H) REFERENCES CENTRO_MEDICO(ID)
)

CREATE TABLE HOSPITAL_ESPECIALIDADES(
	Codigo_Especialidade	INTEGER			NOT NULL,
	Nome_Especialidade		VARCHAR(50)		NOT NULL,
	PRIMARY KEY(Codigo_Especialidade),
	FOREIGN KEY(Nome_Especialidade) REFERENCES HOSPITAL(Especialidade),
)

CREATE TABLE CONTER(
	Tempo					SMALLDATETIME	NOT NULL DEFAULT GETDATE(), 	
	ID_CIDADE				INTEGER			NOT NULL,
	ID_ESPACO_PUBLICO		INTEGER			NOT NULL,
	PRIMARY KEY(Tempo),
	FOREIGN KEY(ID_CIDADE) REFERENCES CIDADE(ID),
	FOREIGN KEY(ID_ESPACO_PUBLICO) REFERENCES ESPACO_PUBLICO(ID)

)

CREATE TABLE CONSTRUIR(
	Tempo					SMALLDATETIME	NOT NULL DEFAULT GETDATE(),
	Preco					INTEGER			NOT NULL,
	ID_CIDADE				INTEGER			NOT NULL,
	ID_CENTRO_MEDICO		INTEGER			NOT NULL,
	PRIMARY KEY(Tempo),
	FOREIGN KEY(ID_CIDADE) REFERENCES CIDADE(ID),
	FOREIGN KEY(ID_CENTRO_MEDICO) REFERENCES CENTRO_MEDICO(ID)
)

CREATE TABLE MANUTENCAO(
	Tempo					SMALLDATETIME	NOT NULL DEFAULT GETDATE(),
	Tempo_Final				SMALLDATETIME	NOT NULL DEFAULT GETDATE(),
	ID_FUNCIONARIO			INTEGER			NOT NULL,
	ID_ESPACO_PUBLICO		INTEGER			NOT NULL,
	PRIMARY KEY(Tempo),
	FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID),
	FOREIGN KEY(ID_ESPACO_PUBLICO) REFERENCES ESPACO_PUBLICO(ID)

)

CREATE TABLE POSSUIR(
	Tempo					SMALLDATETIME	NOT NULL DEFAULT GETDATE(),
	Tempo_Final				SMALLDATETIME	NOT NULL DEFAULT GETDATE(),
	Valorm2					INTEGER			NOT NULL,
	ID_CIDADE				INTEGER			NOT NULL,
	ID_FREGUESIA			INTEGER			NOT NULL,
	PRIMARY KEY(Tempo),
	FOREIGN KEY(ID_CIDADE) REFERENCES CIDADE(ID),
	FOREIGN KEY(ID_FREGUESIA) REFERENCES FREGUESIA(Codigo)

)

CREATE TABLE CONTRATAR_CS( --variaveis iguais - mudar pls
	Tempo					SMALLDATETIME	NOT NULL DEFAULT GETDATE(),
	Salario					INTEGER			NOT NULL,
	ID_CS					INTEGER			NOT NULL,
	ID_FREGUESIA			INTEGER			NOT NULL,
	PRIMARY KEY(Tempo),
	FOREIGN KEY(ID_CS) REFERENCES CENTRO_SAUDE(ID_CS),
	FOREIGN KEY(ID_FREGUESIA) REFERENCES FREGUESIA(Codigo)

)

CREATE TABLE CONTRATAR_H(
	Tempo					SMALLDATETIME	NOT NULL DEFAULT GETDATE(),
	Salario					INTEGER			NOT NULL,
	ID_FUNCIONARIO			INTEGER			NOT NULL,
	ID_HOSPITAL				INTEGER			NOT NULL,
	PRIMARY KEY(Tempo),
	FOREIGN KEY(ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID),
	FOREIGN KEY(ID_HOSPITAL) REFERENCES HOSPITAL(ID_H)

)




